services:
  web:
    image: berrydenhartog/github-webhook:dev
    build: .
    ports:
      - "8000:8000"
    environment:
      - WEBHOOK_SECRET=dummysecret
      - MATTERMOST_URL=https://httpbin.org/post
      - EXPORTER_IDS=mattermost
      - DEBUG=True
      - LOGGING_LEVEL=DEBUG
