services:
  web:
    image: berrydenhartog/github-webhook:dev
    build: .
    ports:
      - "8000:8000"
    environment:
      - GITHUB_WEBHOOK_SECRET=dummysecret
      - CLIENT_URL=https://httpbin.org/post
      - CLIENT_ID=mattermost
      - DEBUG=True
      - LOGGING_LEVEL=DEBUG
