apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - horizontalpodautoscaler.yaml

namespace: tn-ai-validation-playground

namePrefix: github-webhook-

commonLabels:
  app.kubernetes.io/name: github-webhook

buildMetadata: [originAnnotations]
