apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tn-ai-validation-playground

resources:
  - ../../base
  - secret.yaml

images:
  - name: github-webhook-image
    newName: berrydenhartog/github-webhook
    newTag: main

patches:
  - target:
      kind: Ingress
      name: ing
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: github-webhook.apps.digilab.network
      - op: replace
        path: /spec/tls/0/hosts/0
        value: github-webhook.apps.digilab.network
